version: 1.0.{build}
image: Visual Studio 2017
environment:
 global:
  paperkey:
    secure: MxOJZPR1tTkos0f/z1rM4fjHtWmg4kR3B6uAz8u59R5uDteHyeOSFYwATBPonHVC8oSKAWyrtma2Krk1fIXPMJs+FizIDsxh8VhsgMaeNnU=
build_script:
- cmd: >-
    curl -fsS -o keybase_setup_amd64.msi "https://prerelease.keybase.io/keybase_setup_amd64.msi"

    start /wait msiexec.exe /i keybase_setup_amd64.msi   /quiet /l*v keybase.log

    REM type keybase.log
    
    set PATH=%PATH%;%localappdata%\Keybase\

    keybase -v

    echo "loging in to keybase"

    keybase oneshot -u kenkit --paperkey "%paperkey%"

    set FFMPEG=%cd%\ffmpeg\ffmpeg

    echo "FFMPEG DIR:%FFMPEG%" 

    call 7z x  -y -r ffmpeg_dependancies.zip

    git clone keybase://private/kenkit/gui_project --recursive

    cd gui_project
    
    mkdir build
    
    cd build
    
    mkdir OGRE

    set OGRE_DIR=%cd%\OGRE\build\sdk\CMake

    set OGRE_HOME=%cd%\OGRE

    set SDL2_DIR=%OGRE_HOME%\build\sdk\ogredeps\cmake

    echo "Ogre:%OGRE_DIR%"

    set BOOST_ROOT=C:\Libraries\boost_1_67_0

    cmake ../
    
    cmake --build ../build --target cloud_commander_ui